# docker run -it --rm --name customdns -p 172.17.0.1:53:53/udp davidnurdin/customdns
networks:
  test-network:
  host:
    name: "host"
    external: true


services:
    test-service:
        image: debian:latest
        command: ["sh", "-c", "echo 'Hello, World!' && sleep 360000"]
        networks:
        - test-network
        deploy:
          replicas: 3
          restart_policy:
              condition: on-failure

    customdns:
        image: davidnurdin/customdns:latest
        networks:
          - host
        deploy:
          mode: global  # un container par host
